language: go


go:
  - 1.9.x
  - 1.8.x

before_script:
  - go get -t -v github.com/smallnest/glean

script:
 - go test -v .

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always